version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: always
    container_name: server3
#
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - web
